ARG RELVER
FROM centos:8

LABEL vendor="BigSQL" \
    url="https://bigsql.org" \
    release="${RELVER}"
    os.version="8"

ENV LC_ALL en_US.utf-8
ENV LANG en_US.utf-8

RUN yum -y update \
	&& yum -y install \
		--setopt=skip_missing_names_on_install=False \
		bind-utils \
		epel-release \
		gettext \
		hostname \
		procps-ng \
	&& yum -y clean all
